### ISSUE TITLE
Revision of API in relation to strings

### ISSUE THREAD

**Issue by mecha** [Dhii/espresso-interface#4]
## The Problem

Consumers of the interface are not given an inter-operable way of dumping expressions into strings. A use case that demonstrates the need for this feature is using expressions to represent database query conditions, where the expression structure must eventually be translated into a string to be injected into a query.

## Recommended Solution

Make [`ExpressionInterface`] castable into a string.

The best way to do this is by extending [`StringableInterface`] from the [`dhii/stringable-interface`] package, which declares the [`__toString()`] magic method.

[`ExpressionInterface`]: https://github.com/Dhii/expression-interface/blob/master/src/ExpressionInterface.php

[`StringableInterface`]: https://github.com/Dhii/stringable-interface/blob/master/src/StringableInterface.php

[`dhii/stringable-interface`]: https://github.com/Dhii/stringable-interface

[`__toString()`]: http://php.net/manual/en/language.oop5.magic.php#object.tostring

**Comment by XedinUnknown** [comment]
I imagine that en expression is by definition something that can be evaluated, not something that can have a string representation. Therefore, I suggest having some kind of `StringableExpressionInterface`, which extends also the `StringableInterface`.

**Comment by mecha** [comment]
We keep encountering cases where expressions are only used as a hierarchical representation, with the primary purpose being data processing or rendering, rather than evaluation. For example, generating SQL queries, building ASTs, etc.

Creating a `StringableExpressionInterface`, as @XedinUnknown suggested, would have made sense 8 months ago. However recently, both myself and @XedinUnknown had moved onto an approach that provides better SoC - using a renderer.

Different renderers can render the same expression instance in different ways. For example, an "AND" expression with two terms `a` and `b` can be rendered as `a && b` (most GP languages), `a AND b` (SQL, Python), `a, b` (PROLOG ... kinda) or `ab` (boolean algebra). 

What remains to be decided is whether to have `ExpressionInterface#getType()` (or some other similar method) or whether to have an interface for every type, such as an `AndExpressionInterface`.

**Comment by mecha** [comment]
I'm in favour of `ExpressionInterface#getType()`; These are my reasons:

**1) The type is accessible to consumers.**

Interfaces do not give consumers the type. They only allow consumers to check if it **is** or **is not** of a specific type. If a consumer requires the expression type for computation, it needs to first determine what interface it implements, then deduce the type from the interface name, which may be impossible to do as it relies on the naming scheme of the interface's author.

**2) It formally restricts an expression to a single type**

Expressions can only have a single type. Consider `1 + 2`, `a and b`, `x <= 4`. Logical expressions provide `isNegated()` in addition to the type. Using interfaces means that an instance can declare that it is both `AndExpressionInterface` and `GreaterThanExpressionInterface`. Whether allowing multiple types is good or bad does not matter. You may argue for either side. Ultimately, it leads to undefined behavior because it depends on the _order_ of interfaces checked by a consumer.

**3) Implementations not bound to a single type**

Using interfaces, a concrete (or even abstract) class is bound to a type the moment it declares that it `implements XyzExpresisonInterface`. This means that an expression class cannot dynamically determine its type when `getType()` is called. Again, whether this is good or bad does not matter because ultimately it restricts optimizations. Consider this as an example:

```php
<?php

$expr = new AdditionExpression(15, 7);
$expr->getType(); // "addition"

$expr = new AdditionExpression(15, 1);
$expr->getType(); // "increment"
```

**4) Type is overridable via inheritance**

Self-explanatory. An expression class can be extended such that it returns a different value when `getType()` is called. This also means that mocking expression consumers is easier since `getType()` can just be mocked to return a different type, rather than having to mock multiple different interfaces to test consumer behavior against different expression types.

**5) Serialization is easier**

By serializing, I mean any form of textual transformation (JSON, XML, PHP, CSV, ...). The type can be simply exported, in the same way the terms would be exported. Very easy to write serializers that depend on `ExpressionInterface`, since both `getType()` and `getTerms()` are available.

If the type is indicated by the interface implemented, then once again the serializer has to know every single expression interface that can be implemented. This also means that the entire interface FQN has to be included in the serialization, because there's no reliable way to transform an FQN into a simple "type" indicator. Not without another map at least.

Therefore, I propose the following:

* [`ExpressionInterface`] no longer extends [`EvaluableInterface`].
* [`ExpressionInterface`] provides a `getType()` or `getOperator()` or something similar.
* Optionally, common types/operators can be provided as constants.


An `EvaluableExpressionInterface`, that extends [`EvaluableInterface`], can also be created. However, at this point in time, I fail to see a need for it. It also implies the creation of an `EvaluableLogicalExpressionInterface`. At the time of writing, it makes more sense to encourage consumers to depend on [`EvaluableInterface`] if they require evaluation, and then tighten with further `instanceof` checks.

[`dhii/evaluable-interface`]: https://github.com/Dhii/evaluable-interface
[`EvaluableInterface`]: https://github.com/Dhii/evaluable-interface/blob/master/src/EvaluableInterface.php
[`ExpressionInterface`]: https://github.com/Dhii/expression-interface/blob/develop/src/ExpressionInterface.php

**Comment by XedinUnknown** [comment]
I do like the reasoning behind this. However:

**1)** "deduce the type from the interface name, which may be impossible to do as it relies on the naming scheme of the interface's author"
Yes, and there's not a problem with that. If we want to determine whether something is stringable, we check for `instanceof \Dhii\Util\String\StringableInterface`. This is normal. And it doesn't rely on the "naming scheme"; it relies on a name, an FQN, which ensures universal uniqueness, and is *the* way for interoperability.

**2)** "Expressions can only have a single type"
Yes, but. With the new approach, whereby an expression isn't necessarily evaluable, the expression is just data. What that data _means_ is determined by how it is evaluated, If an expression no longer evaluates itself, then it having a single type is irrelevant.

**3)** "Using interfaces, [...] an expression class cannot dynamically determine its type"
This appears to contradict point **2)**. And again, if an expression no longer determines how it is evaluated, then it determining its type is irrelevant.

**4)** "Type is overridable via inheritance"
Yes it is. But should it be? Can a logical expression suddenly become an arithmetic one?

**5)** "Serialization is easier"
Yes, but at the same time less interoperable. With your approach, type codes become volatile, and maybe more importantly proprietary. Therefore, it becomes easier to serialize, but harder to serialize in a standard format.

---

In general, there seems to be confusion with regard to SoC. We need to choose whether we make expressions dumb or smart, but them being both will lead to hell, I'm sure of it. Then, depending on that decision, we can understand how to deal with them.

Like I mentioned earlier, by using interfaces an expression can declare what it **can** do; a renderer of that expression can then choose how to render it. IMHO, it is useless for an expression to have a type, because depending on whether smart or dumb, it may not be up to the expression. Having type as a property of the expression does not say anything about what the expression is capable of, or what properties it has, and therefore in practice I don't see it being very usable: in code, you will check the type, but then, before doing anything more specific (e.g. something that depends on the type) you will check the interface, The type code, even if centralized via constants of a published interface, cannot be reliably tied to any characteristic of the expression that is somehow significant or relevant. On the other hand, checking against a standard and published interface FQN effectively solves all these problems. Yes, the consumer has to know about these FQNs; but this is why it is a published standard, and all such standards are usable in that way.

**Comment by mecha** [comment]
**1)** _"If we want to determine whether something is stringable, we check for instanceof `\Dhii\Util\String\StringableInterface`."_

Yes, but that's checking for capability. A class can either be or not be able to be cast to a string. It is a yes or no question for a **single** interface. The case I'm advocating is that `ExpressionInterface` is no longer something that can be evaluated. It is a data structure. And as such there should _not_ be any functional difference based on the conceptual "type" of the expression. It is a data node that differs by instance, not by implemented interface, because for there to be a functional difference there must first be actual functionality.

**2+3)** _"If an expression no longer evaluates itself, then it having a single type is irrelevant."_ ... _"This appears to contradict point 2)"_

The type is not irrelevant anymore than a UI component's label, a config instance's key, a time object's timestamp, etc. Even if it does not render itself, such things like the aforementioned label may be an intrinsic property of the UI component and does not exist for the single purpose of being rendered. The same thing here. An expression is of a particular type and has terms. Its type is not directly related to rendering. Similar to a UI component's label, it is just _data_, and it is returned from a method. Once you call that method you get **one** value. But that one value can be dynamically calculated. Being able to resolve a single value and having that value not be fixed is not contradictory.

**4)** Perhaps not in the way that you demonstrated in your example. Obviously, it's nonsensical to do that. But it may be considering OK to extend an abstract expression of type `"equals"` to derive an expression of type `"strict_equals"`, for example.

**5)** We've encountered cases before where certain data is constant and standard. If type codes are published as constants in an interface, then "standard" and "proprietary" are well defined without any grey area. We've done this before and is a direct substitute to enums, which are a more formal declaration. We don't have enums, so we settle for interface constants.

----

> In general, there seems to be confusion with regard to SoC. We need to choose whether we make expressions dumb or smart, but them being both will lead to hell, I'm sure of it. Then, depending on that decision, we can understand how to deal with them.

Yes. My proposal is that expressions are nothing more than a data node. The type is an exposable piece of data.

----

> Having type as a property of the expression does not say anything about what the expression is capable of, or what properties it has

> The type code, even if centralized via constants of a published interface, cannot be reliably tied to any characteristic of the expression that is somehow significant or relevant.

Precisely! That's what I'm advocating. The type is not meant to tell you what the expression can do. No more than the terms do. No more than a negation flag does. Depending on an `ExpressionInterface` means _"I am not concerned with evaluation, I just want a hierarchy of expressions"_.

----

> in code, you will check the type, but then, before doing anything more specific (e.g. something that depends on the type) you will check the interface

If you need to do something specific **with** the expression instance, then yes an interface is what you'd need. So far, I can't see a need however. An expression is either used as a node or for evaluation. The former can be satisfied with my proposal. The latter can be satisfied with `EvaluableInterface`.

All expressions are the same - in that they share the same structure and properties, even if they evaluate differently. The very definition of an expression (in computing, not mathematics) is uniform, in that `0`, `"this"`, `$that`, `a + (b * c)` and `answer(42)` are all expressions. They express some value, both explicitly and implicitly. Functional differences do not merit difference interfaces. In fact we use interfaces to **conceal** functional differences under a common API, such that functionality is an implementation detail.

I'm not against expression-specific interfaces if there's a need for them. I just don't see a scenario (at the present time) where a specific expression will need an extended API. _Groups_ of expressions do exist, such as `LogicalExpressionInterface`, and that's only because it exposes negation as a piece of data. For evaluation, even the negation flag does not matter. Something that can be evaluated is, like a `BlockInterface`, aware of its own state and configuration.

At the end of the day, the consumer will depend on an expression **because** it cannot anticipate the type of expression. If it _did know_ that it needs specifically, say, a multiplication, it can just accept a list of `EvaluableInterface` term instances and just do multiplication like so:

```php
function calc_discount($price, EvaluableInterface[] $discounts)
{
    return array_reduce($discounts, function($c, $i) {
        return $c * $i->evaluate();
    }, $price);
}
```

The interfaces we are writing allow the consumer to not know what the expression is.

```php
function calc_discount($price, EvaluableInterfaces $discountExpr)
{
    return $discountExpr->evaluate($price);
}
```

----

> On the other hand, checking against a standard and published interface FQN effectively solves all these problems. Yes, the consumer has to know about these FQNs; but this is why it is a published standard, and all such standards are usable in that way.

Agree. With that reasoning, knowledge of a type code string OR a constant FQN (such as `ExpressionInterface::T_AND`) is usable in the same way.

----

Like I said, I'm not against specific interfaces such as `AndExpressionInterface` or `SubstractionExpressionInterface`, **if and only if** they require a different API.

Why? Because consider the following:

```php
interface AndExpressionInterface extends LogicalExpressionInterface
{
    // (a)
}

function myConsumer(AndExpressionInterface $expr)
{
    // (b)
}
```

(a) What is the purpose of this interface? You may argue that it is formally saying that the expression is an `AND` expression. but is it really? You may document it, you may preach about it, you may depend on it. But delusions aside, there is nothing that formally binds it to be an `AND` expression. It has `getTerms()` that return terms and `isNegated()` that returns the negation flag.

If an implementation also implements `EvaluableInterface`, it will also be able to compute a result for a context value, which can might as well be a square root operation. Yes, it's silly to think that an implementor would do this and it's not a valid point to make. But this example allows me to demonstrate how the consumer should not care about such things.

(b) If it can be evaluated, then just call `evaluate()`, regardless of what type it is. If it's just an expression, then it represents the hierarchy. It has retrievable terms, an exposable type, and if it's a logical expression, it provides the negation flag. Consider just how useful an expression hierarchy is for a lexer and/or parser, to be able to build expressions uniformly. They do not differ in constitution, they only differ by instance. Consider just how useful an evaluable instance is for an interpreter, to not care what the expression type is, to not even care if it's an expression in the first place and just be able to evaluate it.

**Comment by XedinUnknown** [comment]
Ok, you convinced me with the last two paragraphs that checking for a type code may be better than `instanceof`. However, my main point is that an `AND` expression must evaluate as such. How can we tie these two together in a sane way?

**Comment by mecha** [comment]
I'm glad. But as a nice "gotcha", notice how I never mentioned the type in the context of "checking" :trollface: 

I'm not sure how we can enforce particular expression behavior. Up till now I've only been thinking that we shouldn't, since `EvaluableInterface` _just_ evaluates. Am I wrong in thinking we shouldn't care? Are there any cases where you'd want to specifically deal with an expression of a particular type?

**Comment by XedinUnknown** [comment]
It's more that when I add a `new AndExpression([$a, $b])`, I want the result of the evaluation (as performed by an external evaluator) to be that of an `AND`. Otherwise, the expressions can be meaningless, and I would not be able to rely on them.

**Comment by mecha** [comment]
Of course you can rely on them! Not these interfaces specifically, because they're just for hierarchy. But `EvaluableInterface`. `AndExpression` is an implementation, so you cannot depend on it and _"want the result of the evaluation to be that of an `AND`"_.

To me this is like wanting a `FileLoggerInterface`. The whole point of `LoggerInterface` is so that you can just `log()`. Besides, they would both have the same API. It's the same thing here.

The point of having `EvaluableInterface` is to be able to `evaluate()` something. If you as a consumer know that you want an `AND` operation, don't depend on `EvaluableInterface` for the "and" expression, but rather depend on a collection of `EvaluableInterface` instances (its terms), `evaluate()` the `&&` them yourself.

An implementation can do whatever it wants, as long as it fulfills the contract. Of course, any sane developer would give their implementations sane names, but in the end they're just that - names, and only indicate the strategy used to fulfill the contract. These are of no concern to the consumer.

**Comment by mecha** [comment]
This issue can be considered satisfied by PR #8
